<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use ReflectionClass;

class GenerateTypes extends Command
{
    protected $signature = 'gen:types {--output=resources/js/types/generated.ts : Output file path}';

    protected $description = 'Generate TypeScript types from PHP models and API Resources';

    protected array $phpToTsTypeMap = [
        'integer' => 'number',
        'int' => 'number',
        'float' => 'number',
        'double' => 'number',
        'decimal' => 'number',
        'string' => 'string',
        'bool' => 'boolean',
        'boolean' => 'boolean',
        'array' => 'Record<string, unknown>',
        'object' => 'Record<string, unknown>',
        'json' => 'Record<string, unknown>',
        'collection' => 'unknown[]',
        'datetime' => 'string',
        'date' => 'string',
        'date_immutable' => 'string',
        'timestamp' => 'string',
        'encrypted' => 'string',
        'encrypted:array' => 'Record<string, unknown>',
        'encrypted:collection' => 'unknown[]',
        'encrypted:object' => 'Record<string, unknown>',
    ];

    public function handle(): int
    {
        $this->info('Generating TypeScript types...');

        $output = $this->option('output');
        $types = [];

        $types[] = $this->generateModelTypes();
        $types[] = $this->generateResourceTypes();

        $content = implode("\n\n", array_filter($types));

        $header = <<<'TS'
// Auto-generated by `php artisan gen:types`
// Do not edit manually. Run `bun types` to regenerate.

TS;

        File::ensureDirectoryExists(dirname($output));
        File::put($output, $header.$content);

        $this->info("Types generated: {$output}");

        return Command::SUCCESS;
    }

    protected function generateModelTypes(): string
    {
        $models = $this->findModels();
        $output = "// === Models ===\n";

        foreach ($models as $model) {
            try {
                $reflection = new ReflectionClass($model);
                if ($reflection->isAbstract()) {
                    continue;
                }

                $instance = app($model);
                $tableName = $instance->getTable();
                $fillable = $instance->getFillable();
                $hidden = $instance->getHidden();
                $casts = $instance->getCasts();

                $typeName = $this->getModelTypeName($model);
                $fields = [];

                $allFields = array_unique(array_merge($fillable, array_keys($casts)));

                foreach ($allFields as $field) {
                    if (in_array($field, $hidden, true)) {
                        continue;
                    }

                    $tsType = 'unknown';

                    if (isset($casts[$field])) {
                        $castType = strtolower($casts[$field]);
                        $tsType = $this->phpToTsType($castType);
                    } elseif ($field === 'id') {
                        $tsType = 'number';
                    } elseif (Str::endsWith($field, '_at')) {
                        $tsType = 'string';
                    } elseif (Str::endsWith($field, '_id')) {
                        $tsType = 'number';
                    }

                    $nullable = in_array($field, ['email_verified_at', 'last_login_at', 'deleted_at', 'verified_at', 'suspended_at', 'revoked_at', 'fulfilled_at', 'granted_at'], true);
                    $fields[] = "  {$field}".($nullable ? '?' : '').": {$tsType}";
                }

                if (! empty($fields)) {
                    $output .= "export interface {$typeName} {\n".implode("\n", $fields)."\n}\n";
                }
            } catch (\Throwable $e) {
                $this->warn("Skipping {$model}: {$e->getMessage()}");
            }
        }

        return $output;
    }

    protected function generateResourceTypes(): string
    {
        $resources = $this->findResources();
        $output = "// === API Resources ===\n";

        foreach ($resources as $resource) {
            try {
                $reflection = new ReflectionClass($resource);
                if ($reflection->isAbstract()) {
                    continue;
                }

                $typeName = $this->getResourceTypeName($resource);
                $fields = $this->extractResourceFields($resource);

                if (! empty($fields)) {
                    $output .= "export interface {$typeName} {\n".implode("\n", $fields)."\n}\n";
                }
            } catch (\Throwable $e) {
                $this->warn("Skipping {$resource}: {$e->getMessage()}");
            }
        }

        return $output;
    }

    protected function extractResourceFields(string $resourceClass): array
    {
        $fields = [];
        $seen = [];

        try {
            $reflection = new ReflectionClass($resourceClass);
            $method = $reflection->getMethod('toArray');
            $filename = $method->getFileName();

            if (! $filename || ! File::exists($filename)) {
                return [];
            }

            $content = File::get($filename);

            if (preg_match('/return\s*\[(.*?)\];/s', $content, $matches)) {
                $arrayContent = $matches[1];

                preg_match_all("/'(\w+)'\s*=>/", $arrayContent, $keyMatches);

                foreach ($keyMatches[1] as $key) {
                    if (isset($seen[$key])) {
                        continue;
                    }

                    $seen[$key] = true;

                    if (in_array($key, ['when', 'whenLoaded', 'whenNotNull', 'whenNull', 'whenPivotLoaded'], true)) {
                        continue;
                    }

                    $tsType = $this->inferResourceFieldType($arrayContent, $key);
                    $fields[] = "  {$key}: {$tsType}";
                }
            }
        } catch (\Throwable $e) {
            // ignore
        }

        return $fields;
    }

    protected function inferResourceFieldType(string $arrayContent, string $key): string
    {
        $pattern = "/'{$key}'\s*=>\s*(.+?)(?:,|\n)/s";

        if (preg_match($pattern, $arrayContent, $matches)) {
            $value = trim($matches[1]);

            if (str_contains($value, 'whenLoaded') || str_contains($value, 'when(')) {
                return 'unknown';
            }

            if (str_contains($value, 'whenNotNull') || str_contains($value, 'whenNull')) {
                return 'unknown';
            }

            if (str_contains($value, 'new ') && str_contains($value, 'Resource')) {
                return 'unknown';
            }

            if (str_contains($value, 'true') || str_contains($value, 'false')) {
                return 'boolean';
            }

            if (str_contains($value, 'is_current') || str_contains($value, 'isTokenExpired') || str_contains($value, 'isGranted')) {
                return 'boolean';
            }

            if (str_contains($value, '->map') || str_contains($value, '->pluck')) {
                return 'unknown[]';
            }

            if (str_contains($value, '->') && ! str_contains($value, '$this->')) {
                return 'unknown';
            }
        }

        return 'unknown';
    }

    protected function findModels(): array
    {
        $models = [];
        $modelPath = app_path('Models');

        foreach (File::allFiles($modelPath) as $file) {
            if ($file->getExtension() === 'php') {
                $relativePath = str_replace(app_path(), 'App', $file->getPathname());
                $relativePath = str_replace(DIRECTORY_SEPARATOR, '\\', $relativePath);
                $class = str_replace('.php', '', $relativePath);
                $models[] = $class;
            }
        }

        return $models;
    }

    protected function findResources(): array
    {
        $resources = [];
        $resourcePath = app_path('Http/Resources');

        if (! File::exists($resourcePath)) {
            return [];
        }

        foreach (File::allFiles($resourcePath) as $file) {
            if ($file->getExtension() === 'php') {
                $relativePath = str_replace(app_path(), 'App', $file->getPathname());
                $relativePath = str_replace(DIRECTORY_SEPARATOR, '\\', $relativePath);
                $class = str_replace('.php', '', $relativePath);
                $resources[] = $class;
            }
        }

        return $resources;
    }

    protected function getModelTypeName(string $modelClass): string
    {
        $shortName = class_basename($modelClass);

        return $shortName.'Model';
    }

    protected function getResourceTypeName(string $resourceClass): string
    {
        $shortName = class_basename($resourceClass);

        return str_replace('Resource', '', $shortName);
    }

    protected function phpToTsType(string $castType): string
    {
        return $this->phpToTsTypeMap[$castType] ?? 'unknown';
    }
}
