<?php

namespace Database\Seeders;

use App\Models\Compliance\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'code' => 'US',
                'name' => 'United States',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => false,
                'coppa_applicable' => true,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'DE',
                'name' => 'Germany',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'age_of_digital_consent' => 15,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 15,
            ],
            [
                'code' => 'GB',
                'name' => 'United Kingdom',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'ES',
                'name' => 'Spain',
                'age_of_digital_consent' => 14,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 14,
            ],
            [
                'code' => 'IT',
                'name' => 'Italy',
                'age_of_digital_consent' => 14,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 14,
            ],
            [
                'code' => 'NL',
                'name' => 'Netherlands',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'SE',
                'name' => 'Sweden',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'IE',
                'name' => 'Ireland',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'AT',
                'name' => 'Austria',
                'age_of_digital_consent' => 14,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 14,
            ],
            [
                'code' => 'BE',
                'name' => 'Belgium',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'PL',
                'name' => 'Poland',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'PT',
                'name' => 'Portugal',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'age_of_digital_consent' => 15,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 15,
            ],
            [
                'code' => 'DK',
                'name' => 'Denmark',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'FI',
                'name' => 'Finland',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'NO',
                'name' => 'Norway',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => true,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'CH',
                'name' => 'Switzerland',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'CA',
                'name' => 'Canada',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'AU',
                'name' => 'Australia',
                'age_of_digital_consent' => 13,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 13,
            ],
            [
                'code' => 'JP',
                'name' => 'Japan',
                'age_of_digital_consent' => 15,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 15,
            ],
            [
                'code' => 'BR',
                'name' => 'Brazil',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'KR',
                'name' => 'South Korea',
                'age_of_digital_consent' => 14,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 14,
            ],
            [
                'code' => 'IN',
                'name' => 'India',
                'age_of_digital_consent' => 18,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 18,
            ],
            [
                'code' => 'MX',
                'name' => 'Mexico',
                'age_of_digital_consent' => 18,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 18,
            ],
            [
                'code' => 'AR',
                'name' => 'Argentina',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
            [
                'code' => 'CL',
                'name' => 'Chile',
                'age_of_digital_consent' => 18,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 18,
            ],
            [
                'code' => 'CO',
                'name' => 'Colombia',
                'age_of_digital_consent' => 18,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 18,
            ],
            [
                'code' => 'ZA',
                'name' => 'South Africa',
                'age_of_digital_consent' => 18,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 18,
            ],
            [
                'code' => 'NZ',
                'name' => 'New Zealand',
                'age_of_digital_consent' => 16,
                'gdpr_applicable' => false,
                'coppa_applicable' => false,
                'data_retention_days' => 365,
                'requires_parental_consent_below_age' => 16,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
